name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if different (e.g., master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # (Optional) Build step - only needed if you have a build process
      # For a static HTML site like yours, you might skip this if no build is required

      # Upload the files as an artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Must match what deploy-pages expects
          path: .  # Uploads all files in the root directory; adjust if your files are in a subfolder (e.g., 'dist')

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
