name: Deploy Static Website

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          publish_dir: ./  # This points to the root directory where your HTML and CSS files are located
